---
title: "One psychometric curve"
output: html_notebook
---

```{r}
library(tidyverse)
library(quickpsy)
library(broom)
library(cowplot)
library(modelfree)
library(psyphy)
library(modelr)

list.files("R", full.names = TRUE) %>% walk(source)
source("parameters.R")

# read data response -----------------------------------------------------------
dat_resp_ipad <- quickreadfiles(path = "data", 
                                participant = str_pad(1:13, 2, pad = "0"),
                                platform = c("iPad"), 
                                session = c("01", "02")) %>%
  select(session, platform, participant, Duration, Size, Direction,
         Correct, Contrast) %>% 
  rename(duration = Duration, size = Size, contrast = Contrast, 
         direction = Direction, correct = Correct)

dat_resp_crt <- quickreadfiles(path = "data", 
                               participant =str_pad(1:13, 2, pad = "0"),
                               platform = c("CRT"), 
                               session = c("01", "02")) %>%
  select(session, platform, participant, duration, size, direction,
         correct, contrast) %>% 
  mutate(size = if_else(size == 90, 4, 1))


dat_resp <- dat_resp_crt %>% 
  bind_rows(dat_resp_ipad) %>% 
  mutate(duration_signed = duration * direction)
```

### Select two conditions, predict and plot with confidence intervals
```{r}
dat_resp_two <- dat_resp %>% 
  filter(participant =="03",  platform == "CRT")

prob_two <- calculate_proportions(dat_resp_two, correct, 
                                  duration, size) %>% 
  mutate(r = n - k, log10_duration = log10(duration)) %>% 
  ungroup()

model_two_interaction <- glm(cbind(k, r) ~ factor(size) / log10_duration - 1, 
             data = prob_two, 
             family = binomial(mafc.logit(2)))

model_two_interaction <- glm(cbind(k, r) ~ factor(size) + 
                               factor(size):log10_duration - 1, 
             data = prob_two, 
             family = binomial(mafc.logit(2)))
# Alternative (Knoblauch):   
#  factor(size) + factor(size):log10_duration - 1 

log10_duration_seq_size_df <- prob_two %>% distinct(size) %>% 
  crossing(tibble(log10_duration = seq(log10(0.005), 
                                       log10(.25), length.out = 100)))
pre_two_interaction <- augment(model_two_interaction, 
               newdata = log10_duration_seq_size_df,
               type.predict = "response") %>% 
  mutate(fitted_min = .fitted - .se.fit, 
         fitted_max = .fitted + .se.fit)


p <- ggplot() +
  geom_point(data = prob_two, aes(x = log10_duration, y = prob, 
                                  color = factor(size)))+
  # geom_ribbon(data = pre, aes(x = log10_duration,
  #                             ymin = fitted_min, ymax = fitted_max), 
  #             fill = "grey") +
  geom_line(data = pre_two_interaction, aes(x = log10_duration, y = .fitted, 
                                            color = factor(size))) 
p
```
